### ISSUE TITLE
Make file headers sticky

### ISSUE THREAD

**Issue by ericcornelissen** [ecosyste-ms/diff#100]
Request/suggestion to make the file headers in the diff sticky so that it's always easy to tell at which file you're looking.

I noticed this project uses [diff2html](https://github.com/rtfpessoa/diff2html) to render diffs. It seemed to me this is not yet supported by diff2html, so I created an issue for this feature upstream as well, see: https://github.com/rtfpessoa/diff2html/issues/455.

Alternatively, I experimented with _hacking_ sticky file headers into this project without upstream support and I managed to get it working by adding the following snippet to [`app/views/jobs/diff.html.erb`](https://github.com/ericcornelissen/diff/blob/e433250edb1030fe5e22d542667158c73e0ad9d9/app/views/jobs/diff.html.erb):

```html
<style>
  .d2h-file-header {
    position: sticky;
    top: 0;
    z-index: 1;
  }
</style>
```

**Comment by ericcornelissen** [comment]
Sticky file headers are supported as of [`diff2html@v3.4.22`](https://github.com/rtfpessoa/diff2html/releases/tag/3.4.22). It is enabled by default, so given how [`diff2html` is imported](https://github.com/ecosyste-ms/diff/blob/a52cac9366e1b63766a787d710ed8fef38f94f21/app/views/jobs/diff.html.erb#L12) I believe it should start showing up in the `Ecosyste.ms` diff view automatically (I'm not seeing it yet on my end, so I'm leaving this issue open for now). That being said, it could still be considered to add `stickyFileHeaders: true` explicitly in [the `diff2html` configuration](https://github.com/ecosyste-ms/diff/blob/a52cac9366e1b63766a787d710ed8fef38f94f21/app/views/jobs/diff.html.erb#L23).

**Comment by andrew** [comment]
Thanks for that @ericcornelissen, I've updated the config in diff.html.erb now
